services:
  api:
    build: .
    container_name: route-optimizer-api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/route-optimizer
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:4.4
    container_name: mongodb-route-optimizer
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongo-data: