version: '3.8'

services:
  api:
    build: .
    container_name: route-optimizer-api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/route-optimizer-api
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb-route-optimizer
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: